version: '3.2'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer:arm
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:portainer.codeisc.com"
      - "traefik.port=9000"
    networks:
      - traefik

networks:
  traefik:
    external: true
