version: '3.2'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer:arm
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:192.168.1.113"
      - "traefik.port=9000"
    networks:
      - traefik

networks:
  traefik:
    external: true
